import {
  applicationsApi,
  companiesApi,
  educationsApi,
  employeesApi,
  experiencesApi,
  interviewsApi,
  jobsApi,
  notificationsApi,
  profilesApi,
  resumesApi,
  savedJobsApi,
  skillsApi,
  statusHistoriesApi,
} from '../api/resources'

const EMPLOYMENT_TYPES = ['FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'TEMPORARY']
const JOB_STATUSES = ['DRAFT', 'OPEN', 'PAUSED', 'CLOSED', 'EXPIRED']
const APPLICATION_STATUSES = [
  'APPLIED',
  'UNDER_REVIEW',
  'SHORTLISTED',
  'INTERVIEW_SCHEDULED',
  'SELECTED',
  'REJECTED',
  'WITHDRAWN',
]
const INTERVIEW_TYPES = ['PHONE', 'VIDEO', 'ONSITE', 'TECHNICAL', 'HR', 'PANEL']
const INTERVIEW_STATUSES = ['SCHEDULED', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', 'NO_SHOW']
const NOTIFICATION_TYPES = [
  'APPLICATION_STATUS',
  'INTERVIEW_SCHEDULED',
  'JOB_ALERT',
  'MESSAGE',
  'SYSTEM',
]

const money = (value) =>
  value === null || value === undefined || value === '' ? '—' : `₹${Number(value).toLocaleString('en-IN')}`

export const resourceConfigs = [
  {
    key: 'employees',
    title: 'Employees',
    singular: 'Employee',
    icon: 'users',
    group: 'People',
    subtitle: 'Manage employee records, departments and designations.',
    service: employeesApi,
    idKey: 'employeeId',
    filters: [{ key: 'department', label: 'Filter by department' }],
    searchKeys: ['name', 'email', 'department', 'designation'],
    columns: [
      { key: 'employeeId', label: 'ID' },
      { key: 'name', label: 'Employee' },
      { key: 'email', label: 'Email', muted: true },
      { key: 'department', label: 'Department' },
      { key: 'designation', label: 'Designation' },
      { key: 'phone', label: 'Phone', muted: true },
      { key: 'salary', label: 'Salary', render: money },
    ],
    fields: [
      { name: 'name', label: 'Full name', type: 'text', required: true, placeholder: 'e.g. Aarav Sharma' },
      { name: 'email', label: 'Email', type: 'text', required: true, placeholder: 'you@company.com' },
      { name: 'phone', label: 'Phone', type: 'text', placeholder: '+91 98765 43210' },
      { name: 'department', label: 'Department', type: 'text', required: true, placeholder: 'e.g. Engineering' },
      { name: 'designation', label: 'Designation', type: 'text', required: true, placeholder: 'e.g. Frontend Developer' },
      { name: 'salary', label: 'Salary', type: 'number', required: true, placeholder: 'e.g. 75000' },
    ],
  },
  {
    key: 'companies',
    title: 'Companies',
    singular: 'Company',
    icon: 'building',
    group: 'Recruitment',
    subtitle: 'Companies posting jobs on the portal.',
    service: companiesApi,
    searchKeys: ['name', 'industry', 'location', 'website'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Company' },
      { key: 'industry', label: 'Industry' },
      { key: 'location', label: 'Location' },
      { key: 'website', label: 'Website', muted: true },
      { key: 'companySize', label: 'Size', muted: true },
      { key: 'ownerId', label: 'Owner ID' },
    ],
    fields: [
      { name: 'name', label: 'Company name', type: 'text', required: true, placeholder: 'e.g. Acme Corp' },
      { name: 'ownerId', label: 'Owner user ID', type: 'number', required: true, placeholder: 'e.g. 1' },
      { name: 'industry', label: 'Industry', type: 'text', placeholder: 'e.g. Information Technology' },
      { name: 'location', label: 'Location', type: 'text', placeholder: 'e.g. Bengaluru' },
      { name: 'website', label: 'Website', type: 'text', placeholder: 'https://acme.com' },
      { name: 'companySize', label: 'Company size', type: 'text', placeholder: 'e.g. 200-500' },
      { name: 'logoUrl', label: 'Logo URL', type: 'text', placeholder: 'https://…/logo.png' },
      { name: 'description', label: 'Description', type: 'textarea', wide: true, placeholder: 'About the company…' },
    ],
  },
  {
    key: 'jobs',
    title: 'Jobs',
    singular: 'Job',
    icon: 'briefcase',
    group: 'Recruitment',
    subtitle: 'Create and manage job openings.',
    service: jobsApi,
    searchKeys: ['title', 'location', 'description'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'title', label: 'Title' },
      { key: 'companyId', label: 'Company ID' },
      { key: 'location', label: 'Location' },
      { key: 'employmentType', label: 'Type' },
      { key: 'salaryMin', label: 'Salary', render: (v, row) =>
          v === null || v === undefined ? (row.salaryMax ? `Up to ${money(row.salaryMax)}` : '—') : `${money(v)} – ${money(row.salaryMax)}` },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { name: 'title', label: 'Job title', type: 'text', required: true, placeholder: 'e.g. Frontend Developer' },
      { name: 'companyId', label: 'Company', type: 'select', required: true, optionsApi: '/companies' },
      { name: 'location', label: 'Location', type: 'text', placeholder: 'e.g. Remote / Bengaluru' },
      { name: 'employmentType', label: 'Employment type', type: 'select', options: EMPLOYMENT_TYPES },
      { name: 'status', label: 'Status', type: 'select', options: JOB_STATUSES },
      { name: 'salaryMin', label: 'Salary min', type: 'number', placeholder: 'e.g. 600000' },
      { name: 'salaryMax', label: 'Salary max', type: 'number', placeholder: 'e.g. 1200000' },
      { name: 'experienceMin', label: 'Experience min (years)', type: 'number', placeholder: 'e.g. 2' },
      { name: 'experienceMax', label: 'Experience max (years)', type: 'number', placeholder: 'e.g. 5' },
      { name: 'skillIds', label: 'Skills', type: 'multiSelect', optionsApi: '/skills' },
      { name: 'description', label: 'Description', type: 'textarea', required: true, wide: true, placeholder: 'Role responsibilities, requirements…' },
    ],
  },
  {
    key: 'applications',
    title: 'Applications',
    singular: 'Application',
    icon: 'clipboard',
    group: 'Recruitment',
    subtitle: 'Track job applications and their statuses.',
    service: applicationsApi,
    searchKeys: ['status', 'jobId', 'jobSeekerId', 'resumeId'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'jobId', label: 'Job ID' },
      { key: 'jobSeekerId', label: 'Job seeker ID' },
      { key: 'resumeId', label: 'Resume ID' },
      { key: 'status', label: 'Status' },
      { key: 'appliedAt', label: 'Applied at', muted: true },
    ],
    fields: [
      { name: 'jobId', label: 'Job ID', type: 'number', required: true, placeholder: 'e.g. 1' },
      { name: 'jobSeekerId', label: 'Job seeker ID', type: 'number', required: true, placeholder: 'e.g. 2' },
      { name: 'resumeId', label: 'Resume ID', type: 'number', placeholder: 'e.g. 3' },
      { name: 'status', label: 'Status', type: 'select', options: APPLICATION_STATUSES },
    ],
  },
  {
    key: 'interviews',
    title: 'Interviews',
    singular: 'Interview',
    icon: 'video',
    group: 'Recruitment',
    subtitle: 'Schedule interviews and record feedback.',
    service: interviewsApi,
    searchKeys: ['meetingLink', 'feedback'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'applicationId', label: 'Application ID' },
      { key: 'interviewDate', label: 'Date & time' },
      { key: 'interviewType', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'meetingLink', label: 'Meeting link', muted: true },
    ],
    fields: [
      { name: 'applicationId', label: 'Application ID', type: 'number', required: true, placeholder: 'e.g. 1' },
      { name: 'interviewDate', label: 'Interview date & time', type: 'datetime-local', required: true },
      { name: 'interviewType', label: 'Interview type', type: 'select', options: INTERVIEW_TYPES },
      { name: 'status', label: 'Status', type: 'select', options: INTERVIEW_STATUSES },
      { name: 'meetingLink', label: 'Meeting link', type: 'text', placeholder: 'https://meet.example.com/…' },
      { name: 'feedback', label: 'Feedback', type: 'textarea', wide: true, placeholder: 'Interviewer notes…' },
    ],
  },
  {
    key: 'saved-jobs',
    title: 'Saved Jobs',
    singular: 'Saved Job',
    icon: 'bookmark',
    group: 'Recruitment',
    subtitle: 'Jobs saved by job seekers.',
    service: savedJobsApi,
    searchKeys: ['jobId', 'userId'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'jobId', label: 'Job ID' },
      { key: 'userId', label: 'User ID' },
      { key: 'savedAt', label: 'Saved at', muted: true },
    ],
    fields: [
      { name: 'jobId', label: 'Job ID', type: 'number', required: true, placeholder: 'e.g. 1' },
      { name: 'userId', label: 'User ID', type: 'number', required: true, placeholder: 'e.g. 2' },
    ],
  },
  {
    key: 'profiles',
    title: 'Job Seeker Profiles',
    singular: 'Profile',
    icon: 'user',
    group: 'People',
    subtitle: 'Profiles of registered job seekers.',
    service: profilesApi,
    searchKeys: ['headline', 'currentCompany', 'currentLocation'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'userId', label: 'User ID' },
      { key: 'headline', label: 'Headline' },
      { key: 'experienceYears', label: 'Exp (yrs)' },
      { key: 'currentLocation', label: 'Location', muted: true },
      { key: 'expectedSalary', label: 'Expected salary', render: money },
    ],
    fields: [
      { name: 'userId', label: 'User ID', type: 'number', required: true, placeholder: 'e.g. 2' },
      { name: 'headline', label: 'Headline', type: 'text', placeholder: 'e.g. Senior React Developer' },
      { name: 'experienceYears', label: 'Experience (years)', type: 'number', placeholder: 'e.g. 5' },
      { name: 'expectedSalary', label: 'Expected salary', type: 'number', placeholder: 'e.g. 1500000' },
      { name: 'noticePeriod', label: 'Notice period (days)', type: 'number', placeholder: 'e.g. 30' },
      { name: 'currentCompany', label: 'Current company', type: 'text', placeholder: 'e.g. Acme Corp' },
      { name: 'currentLocation', label: 'Current location', type: 'text', placeholder: 'e.g. Bengaluru' },
      { name: 'preferredLocation', label: 'Preferred location', type: 'text', placeholder: 'e.g. Remote' },
      { name: 'profileImageUrl', label: 'Profile image URL', type: 'text', placeholder: 'https://…/avatar.png' },
      { name: 'summary', label: 'Summary', type: 'textarea', wide: true, placeholder: 'Short professional summary…' },
    ],
  },
  {
    key: 'educations',
    title: 'Education',
    singular: 'Education Record',
    icon: 'book',
    group: 'People',
    subtitle: 'Education history of job seekers.',
    service: educationsApi,
    searchKeys: ['degree', 'institution', 'fieldOfStudy'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'jobSeekerId', label: 'Job seeker ID' },
      { key: 'degree', label: 'Degree' },
      { key: 'institution', label: 'Institution' },
      { key: 'fieldOfStudy', label: 'Field of study', muted: true },
      { key: 'startYear', label: 'From' },
      { key: 'endYear', label: 'To' },
      { key: 'percentage', label: '%' },
    ],
    fields: [
      { name: 'jobSeekerId', label: 'Job seeker ID', type: 'number', required: true, placeholder: 'e.g. 2' },
      { name: 'degree', label: 'Degree', type: 'text', required: true, placeholder: 'e.g. B.Tech' },
      { name: 'institution', label: 'Institution', type: 'text', required: true, placeholder: 'e.g. IIT Bombay' },
      { name: 'fieldOfStudy', label: 'Field of study', type: 'text', placeholder: 'e.g. Computer Science' },
      { name: 'startYear', label: 'Start year', type: 'number', placeholder: 'e.g. 2016' },
      { name: 'endYear', label: 'End year', type: 'number', placeholder: 'e.g. 2020' },
      { name: 'percentage', label: 'Percentage', type: 'number', placeholder: 'e.g. 82.5' },
    ],
  },
  {
    key: 'experiences',
    title: 'Experience',
    singular: 'Experience Record',
    icon: 'code',
    group: 'People',
    subtitle: 'Work experience of job seekers.',
    service: experiencesApi,
    searchKeys: ['companyName', 'jobTitle', 'description'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'jobSeekerId', label: 'Job seeker ID' },
      { key: 'companyName', label: 'Company' },
      { key: 'jobTitle', label: 'Job title' },
      { key: 'startDate', label: 'From' },
      { key: 'endDate', label: 'To' },
      { key: 'current', label: 'Current' },
    ],
    fields: [
      { name: 'jobSeekerId', label: 'Job seeker ID', type: 'number', required: true, placeholder: 'e.g. 2' },
      { name: 'companyName', label: 'Company name', type: 'text', required: true, placeholder: 'e.g. Acme Corp' },
      { name: 'jobTitle', label: 'Job title', type: 'text', required: true, placeholder: 'e.g. React Developer' },
      { name: 'startDate', label: 'Start date', type: 'date' },
      { name: 'endDate', label: 'End date', type: 'date' },
      { name: 'current', label: 'Currently working here', type: 'checkbox', checkboxLabel: 'Currently working here' },
      { name: 'description', label: 'Description', type: 'textarea', wide: true, placeholder: 'Responsibilities and achievements…' },
    ],
  },
  {
    key: 'skills',
    title: 'Skills',
    singular: 'Skill',
    icon: 'award',
    group: 'People',
    subtitle: 'Skill catalog used to tag jobs and profiles.',
    service: skillsApi,
    searchKeys: ['name'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Skill' },
    ],
    fields: [
      { name: 'name', label: 'Skill name', type: 'text', required: true, placeholder: 'e.g. React', wide: true },
    ],
  },
  {
    key: 'resumes',
    title: 'Resumes',
    singular: 'Resume',
    icon: 'file',
    group: 'People',
    subtitle: 'Resume files uploaded by job seekers.',
    service: resumesApi,
    searchKeys: ['fileName', 'resumeUrl'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'jobSeekerId', label: 'Job seeker ID' },
      { key: 'fileName', label: 'File name' },
      { key: 'resumeUrl', label: 'URL', muted: true },
      { key: 'isDefault', label: 'Default' },
      { key: 'createdAt', label: 'Uploaded at', muted: true },
    ],
    fields: [
      { name: 'jobSeekerId', label: 'Job seeker ID', type: 'number', required: true, placeholder: 'e.g. 2' },
      { name: 'fileName', label: 'File name', type: 'text', required: true, placeholder: 'e.g. resume.pdf' },
      { name: 'resumeUrl', label: 'Resume URL', type: 'text', required: true, wide: true, placeholder: 'https://…/resume.pdf' },
      { name: 'isDefault', label: 'Default resume', type: 'checkbox', checkboxLabel: 'Set as default resume' },
    ],
  },
  {
    key: 'notifications',
    title: 'Notifications',
    singular: 'Notification',
    icon: 'message',
    group: 'System',
    subtitle: 'Notifications sent to portal users.',
    service: notificationsApi,
    searchKeys: ['notificationMessage', 'type'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'userId', label: 'User ID' },
      { key: 'type', label: 'Type' },
      { key: 'notificationMessage', label: 'Message' },
      { key: 'read', label: 'Read' },
      { key: 'createdAt', label: 'Created at', muted: true },
    ],
    fields: [
      { name: 'userId', label: 'User ID', type: 'number', required: true, placeholder: 'e.g. 2' },
      { name: 'type', label: 'Type', type: 'select', required: true, options: NOTIFICATION_TYPES },
      { name: 'message', label: 'Message', type: 'textarea', required: true, sourceKey: 'notificationMessage', wide: true, placeholder: 'Notification text…' },
      { name: 'read', label: 'Read', type: 'checkbox', checkboxLabel: 'Mark as read' },
    ],
  },
  {
    key: 'status-histories',
    title: 'Status History',
    singular: 'Status History Entry',
    icon: 'clock',
    group: 'System',
    subtitle: 'Audit trail of application status changes.',
    service: statusHistoriesApi,
    searchKeys: ['comment'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'applicationId', label: 'Application ID' },
      { key: 'status', label: 'Status' },
      { key: 'comment', label: 'Comment' },
      { key: 'changedAt', label: 'Changed at', muted: true },
    ],
    fields: [
      { name: 'applicationId', label: 'Application ID', type: 'number', required: true, placeholder: 'e.g. 1' },
      { name: 'status', label: 'Status', type: 'select', options: APPLICATION_STATUSES },
      { name: 'comment', label: 'Comment', type: 'textarea', wide: true, placeholder: 'Why the status changed (max 500 chars)…' },
    ],
  },
]
